var Strings = {
  SELECT_SIZE: "Please select size",
  SELECT_CRUST: "Please select CRUST",
  ADD_TO_CART: "Add to cart",
  CHECKOUT: "Checkout",
  LINK1: "EVERYDAY VALUE",
  LINK2: "BESTSELLERS",
  LINK3: "PASTA PIZZA PARTY",
  LINK4: "VEG PIZZA",
  LINK5: "NON-VEG PIZZA",
  LINK6: "MEALS & COMBOS",
  LINK7: "PIZZA MANIA",
  LINK8: "SPECIALITY CHICKEN",
  LINK9: "SIDES",
  LINK10: "BEVERAGES",
  LIN11: "DESSERT",
  SIZE: "Size",
  CRUST: "Crust",
  CHEESE: "Add cheese @ S-35 M-55 L-75",
  VEG_TOP: "Add veg toppings @ S-30 M-50 L-70 (each)",
  NON_VEG_TOP: "Add non veg toppings @ S-30 M-50 L-70 (each)",
  FRESHPAN: "FreshPan",
  THINCRUST: "ThinCrust",
  CHEESEBURST: "cheezeBurst",
  SMALL: "small",
  MEDIUM: "medium",
  LARGE: "large",
};
export default Strings;
